Add Cradio default
qmk/qmk_configurator pull request #1016
Opened 2021-11-11 23:49 UTC by filterpaper

## Description

Add default layout for Cradio.

2021-11-15 19:46 UTC, noroadsleft requested changes
Updates the keymap so it's the same as running `make cradio:default` from a `qmk_firmware` repository.

2021-11-15 19:46 UTC, noroadsleft commented on public/keymaps/c/cradio_default.json
> +                                       "MO(3)",   "KC_ESC",     "KC_TRNS", "KC_TRNS"
```suggestion
                                       "MO(3)",   "KC_GESC",    "KC_TRNS", "KC_TRNS"
```

2021-11-15 19:46 UTC, noroadsleft commented on public/keymaps/c/cradio_default.json
> +      "KC_TRNS", "KC_F7",    "KC_F8",  "KC_F9",   "KC_F12",     "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS", "KC_TRNS",
```suggestion
      "KC_TRNS", "KC_F1",   "KC_F2",   "KC_F3",   "KC_F10",     "KC_TRNS", "KC_WH_U", "KC_WH_D", "KC_TRNS", "RESET",
      "KC_TRNS", "KC_F4",   "KC_F5",   "KC_F6",   "KC_F11",     "KC_MS_L", "KC_MS_D", "KC_MS_U", "KC_MS_R", "KC_INS",
      "KC_TRNS", "KC_F7",   "KC_F8",   "KC_F9",   "KC_F12",     "KC_TRNS", "KC_BTN1", "KC_BTN2", "KC_TRNS", "KC_TRNS",
```

2021-11-16 03:13 UTC, noroadsleft approved these changes

2021-11-16 03:19 UTC, merged

2021-11-16 03:19 UTC, noroadsleft commented
Thanks!

2021-11-16 03:20 UTC, filterpaper commented
Thank you for the quick review.