Fix Portuguese to use the correct endonym Português
qmk/qmk_configurator pull request #1028
Opened 2021-12-14 06:31 UTC by peepeetee

## Description

2021-12-14 06:35 UTC, fauxpark requested changes

2021-12-14 06:35 UTC, fauxpark commented on src/store/modules/app/state.js
> +    { value: 'pt-BR', label: 'Português' },
```suggestion
    { value: 'pt-BR', label: 'Português (Brasil)' },
```

2021-12-14 06:40 UTC, peepeetee commented
@fauxpark The docs just says Português, we should try to keep them synced somehow. Should I go and make the change over there too?
<img width="74" alt="image" src="https://user-images.githubusercontent.com/43021794/145946230-6ef917b6-898b-4c2c-bf41-b41db5febd92.png">

2021-12-18 19:05 UTC, noroadsleft approved these changes

2021-12-18 19:13 UTC, noroadsleft commented
fauxpark can feel free to disagree with me here, but I don't see any reason that the docs and Configurator have to use the same strings for language names. It's also been quite some time since I worked on docs translations, but I seem to recall that the menu you screen-captured is width-limited in the docs theme we use, and so longer strings get cut off visually anyway.

I'm good with the state of this PR as-is; merging. Thanks!

2021-12-18 19:13 UTC, merged