added keymap for k34
qmk/qmk_configurator pull request #1035
Opened 2021-12-23 11:35 UTC by wongjingping

Adding keymap for k34

## Description

Adding keymap json for k34. Tested on the configurator and it loads.

2021-12-24 09:01 UTC, noroadsleft requested changes
1. The file needs to be renamed to `k34_default.json`:
    `git mv public/keymaps/k/k34.json public/keymaps/k/k34_default.json`
2. Why are there eight layers here when the default keymap in the `qmk_firmware` repository only has three?

2021-12-26 11:22 UTC, wongjingping commented
> 1. The file needs to be renamed to `k34_default.json`:
>    `git mv public/keymaps/k/k34.json public/keymaps/k/k34_default.json`
Done
> 2. Why are there eight layers here when the default keymap in the `qmk_firmware` repository only has three?
Was reusing another keymap. Changed back to 3 for consistency.

2021-12-28 06:16 UTC, noroadsleft approved these changes

2021-12-28 06:20 UTC, merged

2021-12-28 06:21 UTC, noroadsleft commented
Thanks!