Add new keyboard rev_0101, rev_0111, rev_0112 and rev_0113 for keychron.
qmk/qmk_configurator pull request #1057
Opened 2022-01-24 06:56 UTC by lalalademaxiya1

## Description
- Add new keyboard rev_0101, rev_0111, rev_0112 and rev_0113 for keychron.

2022-01-25 00:14 UTC, noroadsleft reviewed
I need to make some changes for these on the `qmk_firmware` side before I can bring these in. All of these boards have issues with their QMK Configurator implementations.

2022-02-24 05:59 UTC, yanfali commented
@noroadsleft bump

2022-02-27 21:31 UTC, noroadsleft requested changes

2022-02-27 21:31 UTC, noroadsleft commented on public/keymaps/k/keychron_q2_rev_0112_default.json
> +      "KC_WAVE", "KC_F1",    "KC_F2",   "KC_F3",   "KC_F4",   "KC_F5",   "KC_F6",   "KC_F7",   "KC_F8",   "KC_F9",   "KC_F10",  "KC_F11",  "KC_F12",  "KC_TRNS",            "KC_TRNS",
```suggestion
      "S(KC_GRV)", "KC_F1",    "KC_F2",   "KC_F3",   "KC_F4",   "KC_F5",   "KC_F6",   "KC_F7",   "KC_F8",   "KC_F9",   "KC_F10",  "KC_F11",  "KC_F12",  "KC_TRNS",            "KC_TRNS",
```

2022-02-27 21:31 UTC, noroadsleft commented on public/keymaps/k/keychron_q2_rev_0113_default.json
> +      "KC_WAVE", "KC_F1",    "KC_F2",   "KC_F3",   "KC_F4",   "KC_F5",   "KC_F6",   "KC_F7",   "KC_F8",   "KC_F9",   "KC_F10",  "KC_F11",  "KC_F12",  "KC_TRNS",            "KC_TRNS",
```suggestion
      "S(KC_GRV)", "KC_F1",    "KC_F2",   "KC_F3",   "KC_F4",   "KC_F5",   "KC_F6",   "KC_F7",   "KC_F8",   "KC_F9",   "KC_F10",  "KC_F11",  "KC_F12",  "KC_TRNS",            "KC_TRNS",
```

2022-02-28 03:08 UTC, lalalademaxiya1 commented on public/keymaps/k/keychron_q2_rev_0112_default.json
> +      "KC_WAVE", "KC_F1",    "KC_F2",   "KC_F3",   "KC_F4",   "KC_F5",   "KC_F6",   "KC_F7",   "KC_F8",   "KC_F9",   "KC_F10",  "KC_F11",  "KC_F12",  "KC_TRNS",            "KC_TRNS",
Thanks so much.💕

2022-02-28 22:12 UTC, noroadsleft commented
I didn't realize until late last night that this PR had merge conflicts, which can't be resolved on the web interface. Will merge PR No. 1090 instead.

2022-02-28 22:12 UTC, closed without merging