Add s_ol/0xc_pad default layout
qmk/qmk_configurator pull request #1059
Opened 2022-01-26 12:54 UTC by s-ol

## Description

This is the default layout for the 0xC.pad macropad.
See also the keyboard PR qmk/qmk_firmware#16057.

2022-04-13 06:07 UTC, s-ol commented
@noroadsleft qmk/qmk_firmware#16057 was merged, so this could be tested now 🙂

2022-04-13 16:03 UTC, noroadsleft requested changes

2022-04-13 16:03 UTC, noroadsleft commented on public/keymaps/s/s_ol_0xc_pad_default.json
> +  "commit": "102185a40214d975054d83d6ca74613373e64f64",
```suggestion
  "commit": "8cc86490aac59a93ece62229cc93097a17420fa5",
```

2022-04-14 16:20 UTC, noroadsleft approved these changes

2022-04-14 16:28 UTC, merged

2022-04-14 16:28 UTC, noroadsleft commented
Thanks!

2022-04-14 16:30 UTC, s-ol commented
Thank *you*! 🙂