Added GMK Hazakura colorway
qmk/qmk_configurator pull request #1062
Opened 2022-01-30 07:00 UTC by HorrorTroll

## Description

Added GMK Hazakura colorway, I was asking for permission and he approved for me to open pr.

![image](https://user-images.githubusercontent.com/24840279/151690065-e3dcb931-3e00-43bc-8939-91361269f2cf.png)

2022-02-15 02:21 UTC, noroadsleft requested changes
I was dissatisfied with the color contrast as originally submitted. It looks great but I found it hard to read, and I have 20/20 vision.

before / after:
![image](https://user-images.githubusercontent.com/18669334/153980176-8dbdbe96-3fb8-4cee-abfc-856fac6a8c83.png)

(I also may iterate on this in another PR.)

2022-02-15 02:21 UTC, noroadsleft commented on src/scss/colorways.scss
> +  color: $color-pantone-2346C;
```suggestion
  color: darken($color-pantone-2346C, 10%);
```

2022-02-15 02:21 UTC, noroadsleft commented on src/scss/colorways.scss
> +  color: $color-pantone-2346C;
```suggestion
  color: darken($color-pantone-2346C, 10%);
```

2022-02-15 02:21 UTC, noroadsleft commented on src/scss/colorways.scss
> +  color: $color-pantone-182C;
```suggestion
  color: lighten($color-pantone-182C, 10%);
```

2022-02-15 06:33 UTC, HorrorTroll commented
Thanks, I'm just resolving those issue. Could you please re-check?

2022-02-16 20:51 UTC, noroadsleft approved these changes

2022-02-16 20:51 UTC, noroadsleft commented
That'll do, thanks.

2022-02-16 20:51 UTC, merged