Add drewkeys/iskar default layout
qmk/qmk_configurator pull request #1100
Opened 2022-03-10 05:16 UTC by drewpyun

## Description
Added the default layout to iskar. added the iskar_default.json to keymaps folder (under "i").
Initial PR for QMK files are here -> https://github.com/qmk/qmk_firmware/pull/16562

2022-03-10 05:20 UTC, fauxpark requested changes

2022-03-10 05:20 UTC, fauxpark commented on public/keymaps/i/iskar_default.json
> +      "KC_LCTRL", "KC_LGUI", "KC_LALT",        "KC_SPC",                    "MO(1)", "KC_RCTRL",                   "KC_LEFT", "KC_DOWN", "KC_RGHT"
```suggestion
      "KC_LCTL", "KC_LGUI", "KC_LALT",        "KC_SPC",                    "MO(1)", "KC_RCTL",                   "KC_LEFT", "KC_DOWN", "KC_RGHT"
```

2022-03-10 05:20 UTC, fauxpark commented on public/keymaps/i/iskar_default.json
> +      "KC_GRAVE", "KC_F1", "KC_F2", "KC_F3", "KC_F4", "KC_F5", "KC_F6", "KC_F7", "KC_F8",  "KC_F9",   "KC_F10",     "KC_F11",  "KC_F12",   "KC_TRNS",   "KC_TRNS",  "KC_TRNS",
```suggestion
      "KC_GRV", "KC_F1", "KC_F2", "KC_F3", "KC_F4", "KC_F5", "KC_F6", "KC_F7", "KC_F8",  "KC_F9",   "KC_F10",     "KC_F11",  "KC_F12",   "KC_TRNS",   "KC_TRNS",  "KC_TRNS",
```

2022-03-11 05:11 UTC, noroadsleft requested changes
The file contents are fine, but this file needs to be moved/renamed to work as intended:

```
git mv public/keymaps/i/iskar_default.json public/keymaps/d/drewkeys_iskar_default.json
git commit -m "rename to public/keymaps/d/drewkeys_iskar_default.json"
```

2022-03-12 02:47 UTC, noroadsleft requested changes

2022-03-12 02:47 UTC, noroadsleft commented on public/keymaps/d/drewkeys_iskar_default.json
> +      "KC_LCTRL", "KC_LGUI", "KC_LALT",        "KC_SPC",                    "MO(1)", "KC_RCTRL",                   "KC_LEFT", "KC_DOWN", "KC_RGHT"
```suggestion
      "KC_LCTL",  "KC_LGUI", "KC_LALT",        "KC_SPC",                    "MO(1)", "KC_RCTL",                    "KC_LEFT", "KC_DOWN", "KC_RGHT"
```

2022-03-12 02:47 UTC, noroadsleft commented on public/keymaps/d/drewkeys_iskar_default.json
> +      "KC_GRAVE", "KC_F1", "KC_F2", "KC_F3", "KC_F4", "KC_F5", "KC_F6", "KC_F7", "KC_F8",  "KC_F9",   "KC_F10",     "KC_F11",  "KC_F12",   "KC_TRNS",   "KC_TRNS",  "KC_TRNS",
```suggestion
      "KC_GRV",   "KC_F1", "KC_F2", "KC_F3", "KC_F4", "KC_F5", "KC_F6", "KC_F7", "KC_F8",  "KC_F9",   "KC_F10",     "KC_F11",  "KC_F12",   "KC_TRNS",   "KC_TRNS",  "KC_TRNS",
```

2022-03-12 09:54 UTC, noroadsleft approved these changes

2022-03-12 09:57 UTC, merged