add dcs midnight and twilight version by matt3o
qmk/qmk_configurator pull request #1122
Opened 2022-05-28 11:46 UTC by alinelena

![test-2](https://user-images.githubusercontent.com/3306823/170824076-16421523-7ea7-44fb-8d81-6e1212cb9697.gif)

2022-05-30 22:36 UTC, noroadsleft requested changes

2022-05-30 22:36 UTC, noroadsleft commented on src/scss/dcs-abs.scss
> +$color-dcs-abs-mid-alpha: #30312e;
This file isn't necessary; all these colors already exist in Configurator.

```
git rm src/scss/dcs-abs.scss
```

2022-05-30 22:36 UTC, noroadsleft commented on src/components/BaseKey.vue
> +@import '../scss/dcs-abs';
The Signature Plastics / Pimp My Keyboard color list is at `src/scss/sp-abs.scss`.

```suggestion
```

2022-05-30 22:36 UTC, noroadsleft commented on src/components/colorways/index.js
> +  list: [...dsa, ...sa, ...gmk, ...jtk, ...kat, ...mt3, ...dcs],
Putting DCS first will keep the list in alphabetical order.

```suggestion
  list: [...dcs, ...dsa, ...sa, ...gmk, ...jtk, ...kat, ...mt3],
```

2022-05-30 22:36 UTC, noroadsleft commented on src/scss/colorways.scss
> +  color: $color-dcs-abs-mid-accent-cyan;
The following suggestions swap out the color codes for the existing codes (they're the exact colors in each case).

```suggestion
  background: $color-sp-abs-GB;
  color: $color-sp-abs-VCO;
```

2022-05-30 22:36 UTC, noroadsleft commented on src/scss/colorways.scss
> +  color: $color-dcs-abs-mid-accent-cyan;
```suggestion
  background: $color-sp-abs-GEW;
  color: $color-sp-abs-VCO;
```

2022-05-30 22:36 UTC, noroadsleft commented on src/scss/colorways.scss
> +  color: $color-dcs-abs-mid-accent-yellow;
```suggestion
  background: $color-sp-abs-GEW;
  color: $color-sp-abs-YCH;
```

2022-05-30 22:36 UTC, noroadsleft commented on src/scss/colorways.scss
> +  color: $color-dcs-abs-mid-accent-cyan;
```suggestion
  background: $color-sp-abs-GB;
  color: $color-sp-abs-VCO;
```

2022-05-30 22:36 UTC, noroadsleft commented on src/scss/colorways.scss
> +  color: $color-dcs-abs-black;
```suggestion
  background: $color-sp-abs-VCO;
  color: $qmk-black;
```

2022-05-30 22:51 UTC, noroadsleft commented
Also will need a rebase on current `qmk:master`; this PR conflicts with the MT3 LOTR/3277 merge.

2022-05-31 03:41 UTC, alinelena commented
i messed the rebase... will be faster to read the stuff in a clean pr.

2022-05-31 04:49 UTC, noroadsleft approved these changes

2022-05-31 04:50 UTC, merged

2022-05-31 04:50 UTC, noroadsleft commented
Thanks!