Add mini36
qmk/qmk_configurator pull request #1200
Opened 2022-10-23 00:15 UTC by controller-works

## Description

Add support for mini36 keyboard by Controller Works. The mini36 is a low profile, split, ergonomic keyboard based on the RP2040 processor. It has 16MB of flash memory and an OLED on each half.

2022-10-27 03:33 UTC, noroadsleft requested changes

2022-10-27 03:33 UTC, noroadsleft commented on public/keymaps/c/controllerworks_mini36_default.json
> +           "LCTL_T()",    "KC_S",    "KC_D",    "KC_F",    "KC_G",                         "KC_H",    "KC_J",    "KC_K",    "KC_L", "KC_SCLN",
```suggestion
       "LCTL_T(KC_A)",    "KC_S",    "KC_D",    "KC_F",    "KC_G",                         "KC_H",    "KC_J",    "KC_K",    "KC_L", "KC_SCLN",
```

2022-10-28 18:00 UTC, controller-works commented
@noroadsleft I accepted all change suggestions.

2022-10-29 16:41 UTC, noroadsleft approved these changes

2022-10-29 16:42 UTC, merged

2022-10-29 16:42 UTC, noroadsleft commented
Thanks!