Add latam spanish keyboard layout
qmk/qmk_configurator pull request #1324
Opened 2023-11-23 15:12 UTC by JuanoD

Latin america uses a different keyboard from Spain. It makes it really hard to configure a keyboard.

## Description

Added spanish (latam) layout.
Changed keys font to monospace to handle keys with AltGr modifiers correctly.

![image](https://github.com/qmk/qmk_configurator/assets/3674588/ef441560-14e1-43e2-93fc-1e342ce5739a)
![image](https://github.com/qmk/qmk_configurator/assets/3674588/87b68a7d-b2bf-4859-b586-672a7e5fe969)

2023-11-23 15:15 UTC, fauxpark requested changes
The corresponding header file does not exist in the qmk_firmware repository. You need to open a PR there first.

2023-11-25 17:55 UTC, JuanoD commented
Here is the PR to qmk_firmware https://github.com/qmk/qmk_firmware/pull/22542

2024-03-19 22:06 UTC, JuanoD commented
Is there anything stopping this from being merged?
My commit for the firmware headers is already merged into main.
If any other changes are needed, let me know.

2024-03-20 07:48 UTC, yanfali commented
This looks pretty good, but I'm hardly an expert. @precondition any objections?

2024-03-20 15:29 UTC, precondition requested changes
Comparing the output of `node qmk_configurator/src/i18n/keymap_extras/convert_keymap_extras_header.js qmk_firmware/quantum/keymap_extras/keymap_spanish_latin_america.h` and the suggested file `qmk_configurator/src/i18n/keymap_extras/keymap_spanish_latin_america.js` unearthed multiple inconsistencies between what is said in the keymap header in QMK firmware repository and what is shown here.

I'm getting the sense you manually edited the pre-existing file for the Spanish host OS layout, but the intended, albeit undocumented, workflow is to run the `convert_keymap_extras_header.js` on a keymap_extras header file from qmk_firmware.

2024-03-20 15:29 UTC, precondition commented on src/i18n/keymap_extras/keymap_spanish_latin_america.js
> +  'ALGR(KC_NUHS)': { name: '`', title: 'ES_ACUT' },
```suggestion
  'ALGR(KC_NUHS)': { name: '`', title: 'ES_GRV (dead)' },
```

WARNING: `ES_GRV` would be the canonical alias for a dead grave key but it was forgotten in https://github.com/qmk/qmk_firmware/pull/22542 — [see how there is nothing after the declaration of `ES_CIRC`](https://github.com/JuanoD/qmk_firmware/blob/9aa4049d5603c67e7d4db564d25d1b4eab35c235/data/constants/keycodes/extras/keycodes_spanish_latin_america_0.0.1.hjson#L335) — so `ES_GRV` technically does not exist yet in qmk_firmware, and should be added.

2024-03-24 20:40 UTC, precondition approved these changes

2024-03-24 23:16 UTC, yanfali commented
Thank you so much @precondition I have no objections to this being merged. @noroadsleft please merge if you have no objections

2024-03-24 23:17 UTC, yanfali approved these changes
Good to go

2024-03-24 23:18 UTC, yanfali commented
@fauxpark either dismiss your review or approve. Thanks

2024-03-24 23:34 UTC, fauxpark approved these changes

2024-03-25 03:02 UTC, noroadsleft requested changes
Just one thing...

2024-03-25 03:04 UTC, JuanoD commented on src/i18n/keymap_extras/keymap_spanish_latin_america.js
> +  'S(KC_NUHS)': { name: ']', title: 'ES_RBCR' },
Ready

2024-03-25 04:06 UTC, noroadsleft approved these changes

2024-03-25 04:12 UTC, merged

2024-03-25 04:13 UTC, noroadsleft commented
¡Gracias por tu contribución! :smile: