Add Helix rev3 default keymaps
qmk/qmk_configurator pull request #829
Opened 2020-10-12 14:53 UTC by MakotoKurauchi

Add the default keymap for Helix rev3 following qmk/qmk_firmware#10297.

Thanks!

2020-10-13 20:46 UTC, noroadsleft requested changes
Just these two things; looks good otherwise!

2020-10-13 20:46 UTC, noroadsleft commented on public/keymaps/h/helix_rev3_4rows_default.json
> +      "KC_TRNS",
```suggestion
      "EEP_RST",
```

2020-10-13 20:46 UTC, noroadsleft commented on public/keymaps/h/helix_rev3_5rows_default.json
> +      "KC_TRNS",
```suggestion
      "EEP_RST",
```

2020-10-13 23:29 UTC, MakotoKurauchi commented on public/keymaps/h/helix_rev3_5rows_default.json
> +      "KC_TRNS",
thanks

2020-10-14 04:02 UTC, noroadsleft approved these changes

2020-10-14 04:02 UTC, merged

2020-10-14 04:02 UTC, noroadsleft commented
Thanks!