Add dingo fact
qmk/qmk_configurator pull request #841
Opened 2020-11-09 19:57 UTC by Erovia

It's most important this gets merged.

2020-11-09 19:59 UTC, tzarc approved these changes
I can only hit approve once, sadly.

2020-11-09 19:59 UTC, noroadsleft requested changes

2020-11-09 19:59 UTC, noroadsleft commented on src/potato-facts.js
> +  'F**k mate, that\'s drier than a dead dingo\'s donger.'
```suggestion
  'F**k mate, that\'s drier than a dead dingo\'s donger.',
```

2020-11-09 20:01 UTC, tzarc requested changes

2020-11-09 20:01 UTC, tzarc commented on src/potato-facts.js
> +  'F**k mate, that\'s drier than a dead dingo\'s donger.',
```suggestion
  'F**k mate, that potato\'s drier than a dead dingo\'s donger.',
```

2020-11-09 21:14 UTC, yanfali approved these changes

2021-05-14 17:08 UTC, yanfali commented
@Erovia rebase this on latest master so it'll build again. We stopped using travis.

2022-02-24 05:58 UTC, yanfali commented
closing

2022-02-24 05:58 UTC, closed without merging