add GMK Vaporwave
qmk/qmk_configurator pull request #853
Opened 2020-12-01 11:57 UTC by akatopo

Adds vaporwave colorway. Uses colors from this [GH thread](https://geekhack.org/index.php?topic=99875.0).
Had to lighten the original pink color and change the font weight to bold as the contrast was very bad (see screenshots below). Coincidentally it looks more like the real thing 😄 

![orig-pink](https://user-images.githubusercontent.com/2387645/100737259-988aff80-33dc-11eb-927d-474d00dbbcc9.png)
![lighter-pink](https://user-images.githubusercontent.com/2387645/100737279-9de84a00-33dc-11eb-8d19-5c9351efdd9d.png)

2020-12-01 17:13 UTC, yanfali commented
Needs permission from the original designer. I'll leave it to @noroadsleft to work with you about the colors. Honestly, it doesn't look very good on screen tbh. It works much better as a physical object. legibility is more important than color accuracy for a UI.

2020-12-03 08:42 UTC, akatopo commented
Of course the PR(#843) that I tried to emulate was from a designer 😅. Asked NP for permission on GH:

<img width="1335" alt="permission proof" src="https://user-images.githubusercontent.com/2387645/100984727-c0e93a00-3553-11eb-83d7-771b5624b623.png">

Tried tweaking the pink a bit more, leaving a screenshot

![Screen Shot 2020-12-02 at 1 27 58 PM](https://user-images.githubusercontent.com/2387645/100984992-19203c00-3554-11eb-8444-384bf2c13a97.png)

2020-12-05 03:31 UTC, noroadsleft commented
> ![Screen Shot 2020-12-02 at 1 27 58 PM](https://user-images.githubusercontent.com/2387645/100984992-19203c00-3554-11eb-8444-384bf2c13a97.png)

This looks pretty good, but doesn't seem to match the current state of this PR. Did you forget to `git push`?

2020-12-05 12:06 UTC, akatopo commented
> > ![Screen Shot 2020-12-02 at 1 27 58 PM](https://user-images.githubusercontent.com/2387645/100984992-19203c00-3554-11eb-8444-384bf2c13a97.png)
> 
> This looks pretty good, but doesn't seem to match the current state of this PR. Did you forget to `git push`?

just waiting on feedback, pushed :-)

2020-12-06 08:50 UTC, noroadsleft requested changes

2020-12-06 08:50 UTC, noroadsleft commented on src/scss/colorways.scss
> +    background: lighten(#6244bb, 10%);
Color shift this the other way to increase the contrast.

```suggestion
    background: darken(#6244bb, 10%);
```

2020-12-08 01:20 UTC, noroadsleft approved these changes

2020-12-08 01:20 UTC, noroadsleft commented
I'll probably want to adjust the colors further later on to improve the contrast, but this will do for now.

Thanks!

2020-12-08 01:21 UTC, merged