New Breeze Rev1 default
qmk/qmk_configurator pull request #878
Opened 2021-02-01 05:24 UTC by eithanshavit

## Description
Adding a new default keymap for Breeze Rev1.
Also, matching the Rev0 keymap with the commit hash state.

2021-02-02 23:31 UTC, noroadsleft requested changes
I also note that you have the `LOWER`/`MO(1)` and `RAISE`/`MO(2)` keycodes in opposite order from how they are on `qmk/qmk_firmware`, but the `qmk_firmware` keymap should be updated to match this behaviour IMO, because the `RAISE` keycode actually blocks access to `KC_P0` on that side anyway.

2021-02-02 23:31 UTC, noroadsleft commented on public/keymaps/a/afternoonlabs_breeze_rev1_default.json
> +   "commit": "b32b928ff3dea8a3d396ff44d491bb3d4a95a2c8",
This change should also go on the rev0 keymap.

```suggestion
   "commit": "64da7413a0c2b3ea555288f5d296e3a98a0da6b4",
```

2021-02-03 00:31 UTC, eithanshavit commented
Thanks @noroadsleft, I've committed the new hash. 
Also, thanks for the catch on the MO order, it makes sense to update qmk_firmware. I'll do it in a separate PR.

2021-02-03 01:11 UTC, eithanshavit commented
Updated `qmk_firmware` to match in https://github.com/qmk/qmk_firmware/pull/11779

2021-02-03 12:40 UTC, noroadsleft approved these changes

2021-02-03 12:40 UTC, merged

2021-02-03 12:41 UTC, noroadsleft commented
Thanks!