Adding initial support for Big-Ass Enter.
qmk/qmk_configurator pull request #922
Opened 2021-05-12 20:28 UTC by krautcat

Adding initial support for Big-Ass Enter

## Description

This changed introduces support of the Big-Ass Enter measured as key with height 2 in units and width in 2.25 units.

2021-05-12 23:07 UTC, fauxpark requested changes

2021-05-12 23:07 UTC, fauxpark commented on src/components/BaseKey.vue
> +  }
```suggestion
  if (unith === 2) {
    if (unitw == 1.25) {
      return 'kiso';
    } else if (unitw == 2.25) {
      return 'kbae';
    }
  }
```

2021-05-13 09:15 UTC, krautcat commented on src/components/BaseKey.vue
> +  }
Fixed.

2021-05-13 09:21 UTC, fauxpark approved these changes

2021-05-13 18:41 UTC, noroadsleft approved these changes

2021-05-13 18:41 UTC, noroadsleft commented
Looks great!

![image](https://user-images.githubusercontent.com/18669334/118171517-26353700-b3e0-11eb-8064-226301eb528b.png)

2021-05-13 18:55 UTC, yanfali commented on src/components/BaseKey.vue
> +    if (unitw == 1.25) {
change these to === please

2021-05-13 18:56 UTC, yanfali commented on src/components/BaseKey.vue
> +    } else if (unitw == 2.25) {
same

2021-05-13 18:57 UTC, yanfali requested changes
Looks good. couple of comments and then I'll approve.

2021-05-14 15:44 UTC, krautcat commented on src/components/BaseKey.vue
> +    if (unitw == 1.25) {
Fixed in the next commit.

2021-05-14 15:44 UTC, krautcat commented on src/components/BaseKey.vue
> +    } else if (unitw == 2.25) {
Fixed in the next commit.

2021-05-14 16:34 UTC, yanfali commented
@krautcat  can you run `yarn prettier:fix` ? you have a formatting issue. Then commit that fix. Thanks

2021-05-14 16:50 UTC, krautcat commented
@yanfali seems formatting issue is fixed now. Sorry for overlooking it.

2021-05-14 17:01 UTC, yanfali approved these changes
Thanks for your contribution

2021-05-14 17:01 UTC, merged