rename and update keymap for handwired/evk in the QMK configurator
qmk/qmk_configurator pull request #936
Opened 2021-06-03 15:21 UTC by YangPiCui

title says all :)

2021-06-03 15:21 UTC, YangPiCui commented
https://github.com/qmk/qmk_firmware/pull/13094

2021-06-12 02:28 UTC, noroadsleft requested changes

2021-06-12 02:28 UTC, noroadsleft commented on public/keymaps/h/handwired_evk_v0_1_x_default.json
> +      "KC_1",     "KC_2",     "KC_3",     "KC_4",     "KC_5",     "KC_GRV",        "KC_ESC",   "KC_PSCR",   "TG(1)",    "KC_CAPS",        "KC_SLSH",  "KC_6",     "KC_7",     "KC_8",     "KC_9",     "
```suggestion
      "KC_1",     "KC_2",     "KC_3",     "KC_4",     "KC_5",     "KC_GRV",        "KC_ESC",   "KC_PSCR",   "TG(1)",    "KC_CAPS",        "KC_BSLS",  "KC_6",     "KC_7",     "KC_8",     "KC_9",     "KC_0",
```

2021-06-12 02:28 UTC, noroadsleft commented on public/keymaps/h/handwired_evk_v0_1_x_default.json
> +      "KC_Z",     "KC_X",     "KC_C",     "KC_V",     "KC_B",                      "KC_F9",    "KC_F10",    "KC_F11",   "KC_F12",                     "KC_N",     "KC_M",     "KC_COMM",  "KC_DOT",   "
```suggestion
      "KC_Z",     "KC_X",     "KC_C",     "KC_V",     "KC_B",                      "KC_F9",    "KC_F10",    "KC_F11",   "KC_F12",                     "KC_N",     "KC_M",     "KC_COMM",  "KC_DOT",   "KC_SLSH", 
```

2021-06-12 02:28 UTC, noroadsleft commented on public/keymaps/h/handwired_evk_v0_1_x_default.json
> +      "KC_1",     "KC_2",     "KC_3",     "KC_4",     "KC_5",     "KC_GRV",        "KC_ESC",   "KC_PSCR",   "TG(1)",    "KC_CAPS",        "KC_SLSH",  "KC_6",     "KC_7",     "KC_8",     "KC_9",     "
```suggestion
      "KC_1",     "KC_2",     "KC_3",     "KC_4",     "KC_5",     "KC_GRV",        "KC_ESC",   "KC_PSCR",   "TG(1)",    "KC_CAPS",        "KC_BSLS",  "KC_6",     "KC_7",     "KC_8",     "KC_9",     "KC_0",
```

2021-06-12 02:28 UTC, noroadsleft commented on public/keymaps/h/handwired_evk_v0_1_x_default.json
> +      "KC_Z",     "KC_M",     "KC_C",     "KC_V",     "KC_B",                      "KC_F9",    "KC_F10",    "KC_F11",   "KC_F12",                     "KC_W",     "KC_G",     "KC_COMM",  "KC_DOT",   "
```suggestion
      "KC_Z",     "KC_M",     "KC_C",     "KC_V",     "KC_B",                      "KC_F9",    "KC_F10",    "KC_F11",   "KC_F12",                     "KC_W",     "KC_G",     "KC_COMM",  "KC_DOT",   "KC_SLSH", 
```

2021-06-12 02:43 UTC, YangPiCui commented
Thanks for the commit suggestion! It was a good catch.

2021-06-12 02:55 UTC, noroadsleft reviewed
I'll have one more suggestion once the `qmk_firmware` PR is merged.

2022-02-24 05:58 UTC, yanfali commented
@noroadsleft this still relevant?

2022-02-27 20:29 UTC, noroadsleft commented
@yanfali The requisite PR (https://github.com/qmk/qmk_firmware/pull/13094) was closed as stale due to modified submodules. If the PR is reworked to fix that this can be reopened.

2022-02-27 20:29 UTC, closed without merging