hatchback+suv
qmk/qmk_configurator pull request #942
Opened 2021-06-29 02:22 UTC by AlisGraveNil

## Description

2021-06-29 02:25 UTC, AlisGraveNil commented
I don't remember the instructions for how to get the CLI to spit out the commit number

2021-07-09 21:09 UTC, noroadsleft requested changes

2021-07-09 21:09 UTC, noroadsleft commented on public/keymaps/c/clawsome_hatchback_default.json
> +      "KC_LCTL", "KC_LGUI", "KC_LALT",            "KC_SPC",               "KC_SPC",           "KC_SPC",             "KC_RALT"  "KC_RGUI", "KC_MENU", "KC_RCTL",               "KC_LEFT", "KC_DOWN", "KC
```suggestion
      "KC_LCTL", "KC_LGUI", "KC_LALT",            "KC_SPC",               "KC_SPC",           "KC_SPC",             "KC_RALT", "KC_RGUI", "KC_MENU", "KC_RCTL",               "KC_LEFT", "KC_DOWN", "KC_RGHT"
```

2021-07-09 21:09 UTC, noroadsleft commented on public/keymaps/c/clawsome_suv_default.json
> +  "commit": "x",
```suggestion
  "commit": "22cd151fc359f48d75e361bd46a25ab6b40425fa",
```

2021-07-09 21:09 UTC, noroadsleft commented on public/keymaps/c/clawsome_hatchback_default.json
> +  "layout": "LAYOUT_all",
```suggestion
  "layout": "LAYOUT",
```

2021-07-09 21:09 UTC, noroadsleft commented on public/keymaps/c/clawsome_suv_default.json
> +  "layout": "LAYOUT_all",
```suggestion
  "layout": "LAYOUT",
```

2021-07-09 21:09 UTC, noroadsleft commented on public/keymaps/c/clawsome_suv_default.json
> +      "KC_LCTL", "KC_LGUI", "KC_LALT",            "KC_SPC",               "KC_SPC",           "KC_SPC",             "KC_RALT"  "KC_RGUI", "KC_MENU", "KC_RCTL",    "KC_LEFT", "KC_DOWN", "KC_RGHT".  "K
```suggestion
      "KC_LCTL", "KC_LGUI", "KC_LALT",            "KC_SPC",               "KC_SPC",           "KC_SPC",             "KC_RALT"  "KC_RGUI", "KC_MENU", "KC_RCTL",    "KC_LEFT", "KC_DOWN", "KC_RGHT",  "KC_P0",              "KC_PDOT",
```

2021-07-11 21:59 UTC, noroadsleft requested changes

2021-07-11 21:59 UTC, noroadsleft commented on public/keymaps/c/clawsome_suv_default.json
> +      "KC_LCTL", "KC_LGUI", "KC_LALT",            "KC_SPC",               "KC_SPC",           "KC_SPC",             "KC_RALT"  "KC_RGUI", "KC_MENU", "KC_RCTL",    "KC_LEFT", "KC_DOWN", "KC_RGHT",  "K
I missed this on the previous review.

```suggestion
      "KC_LCTL", "KC_LGUI", "KC_LALT",            "KC_SPC",               "KC_SPC",           "KC_SPC",             "KC_RALT", "KC_RGUI", "KC_MENU", "KC_RCTL",    "KC_LEFT", "KC_DOWN", "KC_RGHT",  "KC_P0",              "KC_PDOT"
```

2021-07-12 01:38 UTC, noroadsleft approved these changes

2021-07-12 01:38 UTC, noroadsleft commented
Thanks!

2021-07-12 01:38 UTC, merged